// <auto-generated />
using System;
using JAP_Task_Backend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JAP_Task_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210907113900_UpdatedMigration")]
    partial class UpdatedMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JAP_Task_Backend.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Score = 6,
                            VideoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Score = 5,
                            VideoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Score = 4,
                            VideoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Score = 7,
                            VideoId = 2
                        },
                        new
                        {
                            Id = 5,
                            Score = 4,
                            VideoId = 3
                        },
                        new
                        {
                            Id = 6,
                            Score = 5,
                            VideoId = 3
                        },
                        new
                        {
                            Id = 7,
                            Score = 7,
                            VideoId = 4
                        },
                        new
                        {
                            Id = 8,
                            Score = 5,
                            VideoId = 4
                        },
                        new
                        {
                            Id = 9,
                            Score = 7,
                            VideoId = 5
                        },
                        new
                        {
                            Id = 10,
                            Score = 4,
                            VideoId = 5
                        },
                        new
                        {
                            Id = 11,
                            Score = 8,
                            VideoId = 6
                        },
                        new
                        {
                            Id = 12,
                            Score = 5,
                            VideoId = 6
                        },
                        new
                        {
                            Id = 13,
                            Score = 9,
                            VideoId = 7
                        },
                        new
                        {
                            Id = 14,
                            Score = 5,
                            VideoId = 7
                        },
                        new
                        {
                            Id = 15,
                            Score = 8,
                            VideoId = 8
                        },
                        new
                        {
                            Id = 16,
                            Score = 5,
                            VideoId = 8
                        },
                        new
                        {
                            Id = 17,
                            Score = 6,
                            VideoId = 9
                        },
                        new
                        {
                            Id = 18,
                            Score = 3,
                            VideoId = 9
                        },
                        new
                        {
                            Id = 19,
                            Score = 4,
                            VideoId = 10
                        },
                        new
                        {
                            Id = 20,
                            Score = 3,
                            VideoId = 10
                        },
                        new
                        {
                            Id = 21,
                            Score = 4,
                            VideoId = 11
                        },
                        new
                        {
                            Id = 22,
                            Score = 10,
                            VideoId = 11
                        },
                        new
                        {
                            Id = 23,
                            Score = 9,
                            VideoId = 12
                        },
                        new
                        {
                            Id = 24,
                            Score = 4,
                            VideoId = 12
                        },
                        new
                        {
                            Id = 25,
                            Score = 3,
                            VideoId = 13
                        },
                        new
                        {
                            Id = 26,
                            Score = 4,
                            VideoId = 13
                        },
                        new
                        {
                            Id = 27,
                            Score = 8,
                            VideoId = 14
                        },
                        new
                        {
                            Id = 28,
                            Score = 10,
                            VideoId = 14
                        },
                        new
                        {
                            Id = 29,
                            Score = 5,
                            VideoId = 15
                        },
                        new
                        {
                            Id = 30,
                            Score = 9,
                            VideoId = 15
                        },
                        new
                        {
                            Id = 31,
                            Score = 4,
                            VideoId = 16
                        },
                        new
                        {
                            Id = 32,
                            Score = 6,
                            VideoId = 16
                        },
                        new
                        {
                            Id = 33,
                            Score = 5,
                            VideoId = 17
                        },
                        new
                        {
                            Id = 34,
                            Score = 7,
                            VideoId = 17
                        },
                        new
                        {
                            Id = 35,
                            Score = 8,
                            VideoId = 18
                        },
                        new
                        {
                            Id = 36,
                            Score = 8,
                            VideoId = 18
                        },
                        new
                        {
                            Id = 37,
                            Score = 7,
                            VideoId = 19
                        },
                        new
                        {
                            Id = 38,
                            Score = 5,
                            VideoId = 19
                        },
                        new
                        {
                            Id = 39,
                            Score = 7,
                            VideoId = 20
                        },
                        new
                        {
                            Id = 40,
                            Score = 8,
                            VideoId = 20
                        },
                        new
                        {
                            Id = 41,
                            Score = 8,
                            VideoId = 21
                        },
                        new
                        {
                            Id = 42,
                            Score = 6,
                            VideoId = 21
                        },
                        new
                        {
                            Id = 43,
                            Score = 9,
                            VideoId = 22
                        },
                        new
                        {
                            Id = 44,
                            Score = 6,
                            VideoId = 22
                        },
                        new
                        {
                            Id = 45,
                            Score = 8,
                            VideoId = 23
                        },
                        new
                        {
                            Id = 46,
                            Score = 7,
                            VideoId = 23
                        },
                        new
                        {
                            Id = 47,
                            Score = 10,
                            VideoId = 24
                        },
                        new
                        {
                            Id = 48,
                            Score = 9,
                            VideoId = 24
                        },
                        new
                        {
                            Id = 49,
                            Score = 10,
                            VideoId = 25
                        },
                        new
                        {
                            Id = 50,
                            Score = 10,
                            VideoId = 25
                        },
                        new
                        {
                            Id = 51,
                            Score = 6,
                            VideoId = 26
                        },
                        new
                        {
                            Id = 52,
                            Score = 8,
                            VideoId = 26
                        },
                        new
                        {
                            Id = 53,
                            Score = 3,
                            VideoId = 27
                        },
                        new
                        {
                            Id = 54,
                            Score = 4,
                            VideoId = 27
                        },
                        new
                        {
                            Id = 55,
                            Score = 7,
                            VideoId = 28
                        },
                        new
                        {
                            Id = 56,
                            Score = 8,
                            VideoId = 28
                        },
                        new
                        {
                            Id = 57,
                            Score = 9,
                            VideoId = 29
                        },
                        new
                        {
                            Id = 58,
                            Score = 8,
                            VideoId = 29
                        },
                        new
                        {
                            Id = 59,
                            Score = 5,
                            VideoId = 30
                        },
                        new
                        {
                            Id = 60,
                            Score = 6,
                            VideoId = 30
                        });
                });

            modelBuilder.Entity("JAP_Task_Backend.Models.Video", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Saving Private Ryan is a 1998 American epic war film directed by Steven Spielberg and written by Robert Rodat. Set during the Invasion of Normandy in World War II, the film is known for its graphic portrayal of war, especially its depiction of the Omaha Beach assault during the Normandy landings.",
                            ImageUrl = "https://fanart.tv/fanart/movies/857/movieposter/saving-private-ryan-521a5ad8ab73e.jpg",
                            ReleaseDate = new DateTime(1998, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Saving Private Ryan",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dominic Cobb is an industrial spy who instead of breaking into a person's home, office, or even computer, gets the information he needs by getting into the person's mind through their dreams.",
                            ImageUrl = "https://www.syfy.com/sites/syfy/files/styles/1170xauto/public/the-witcher-season-2-poster-vertical.jpg",
                            ReleaseDate = new DateTime(2010, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Description = "The witcher Geralt, a mutated monster hunter, struggles to find his place in a world in which people often prove more wicked than beasts.",
                            ImageUrl = "https://www.syfy.com/sites/syfy/files/styles/1170xauto/public/the-witcher-season-2-poster-vertical.jpg",
                            ReleaseDate = new DateTime(2019, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Witcher",
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Forrest Gump is a 1994 American drama film directed by Robert Zemeckis and written by Eric Roth with comedic aspects. It is based on the 1986 novel of the same name by Winston Groom and stars Tom Hanks, Robin Wright, Gary Sinise, Mykelti Williamson and Sally Field.",
                            ImageUrl = "https://cinecalidad.in/wp-content/uploads/2020/03/forrest-gump-7240-poster-683x1024.jpg",
                            ReleaseDate = new DateTime(1994, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump",
                            Type = 1
                        },
                        new
                        {
                            Id = 5,
                            Description = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
                            ImageUrl = "https://www.new-video.de/co/fightclu.jpg",
                            ReleaseDate = new DateTime(1999, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club",
                            Type = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "Two loose-cannon narcotics cops investigate the flow of Ecstasy into Florida from a Cuban drug cartel.",
                            ImageUrl = "https://i.pinimg.com/736x/f8/a5/5d/f8a55dd993b59363dcf4b6e410305f44--hd-movies-action-movies.jpg",
                            ReleaseDate = new DateTime(1995, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bad Boys",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Description = "Two hip detectives protect a witness to a murder while investigating a case of stolen heroin from the evidence storage room from their police precinct.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.M5Y738m_1kCMg-Fef-fI2gHaLH?pid=ImgDet&rs=1",
                            ReleaseDate = new DateTime(2003, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bad Boys II",
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Description = "Miami detectives Mike Lowrey and Marcus Burnett must face off against a mother-and-son pair of drug lords who wreak vengeful havoc on their city.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.Ox-F7hWGAUkWLucz4B7ggwHaLH?pid=ImgDet&rs=1",
                            ReleaseDate = new DateTime(2020, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Bad Boys For Life",
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            Description = "A family man is drafted to fight in a future war where the fate of humanity relies on his ability to confront the past.",
                            ImageUrl = "https://www.okdrama.com/wp-content/uploads/2021/07/The-Tomorrow-War.jpg",
                            ReleaseDate = new DateTime(2021, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Tomorrow War",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
                            ImageUrl = "https://th.bing.com/th/id/R.795762624b2ebe035d8ebe1000397e70?rik=tM2O0EXzddMb7g&riu=http%3a%2f%2fwww.sf-fan.de%2fwp-content%2fuploads%2f2011%2f07%2fjurassic-park-poster.jpg&ehk=ISz78v6xTLdiIOGEtMFG9Qxj29cLWqZWOeZ9OUA8rGk%3d&risl=&pid=ImgRaw&r=0",
                            ReleaseDate = new DateTime(1993, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            Description = "A research team is sent to the Jurassic Park Site B island to study the dinosaurs there, while an InGen team approaches with another agenda.",
                            ImageUrl = "https://vignette.wikia.nocookie.net/cinemorgue/images/d/d8/11168888_800.jpg/revision/latest?cb=20150519044035",
                            ReleaseDate = new DateTime(1997, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lost World: Jurassic Park",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Description = "A decidedly odd couple with ulterior motives convince Dr. Grant to go to Isla Sorna for a holiday, but their unexpected landing startles the island's new inhabitants.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.mMwLmfEru8a0Y86217RLJwHaLH?pid=ImgDet&rs=1",
                            ReleaseDate = new DateTime(2001, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Park III",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Description = "A new theme park, built on the original site of Jurassic Park, creates a genetically modified hybrid dinosaur, the Indominus Rex, which escapes containment and goes on a killing spree.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.-3smAFf-8f3Xye1-VODc5AHaLH?pid=ImgDet&rs=1",
                            ReleaseDate = new DateTime(2015, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic World",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "When the island's dormant volcano begins roaring to life, Owen and Claire mount a campaign to rescue the remaining dinosaurs from this extinction-level event.",
                            ImageUrl = "https://vignette.wikia.nocookie.net/cinemorgue/images/d/df/322699f120c17c2728457969b59af12c.jpg/revision/latest?cb=20180325190743",
                            ReleaseDate = new DateTime(2018, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic World: Fallen Kingdom",
                            Type = 1
                        },
                        new
                        {
                            Id = 15,
                            Description = "When bitten by a genetically modified spider, a nerdy, shy, and awkward high school student gains spider-like abilities that he eventually must use to fight evil as a superhero after tragedy befalls his family.",
                            ImageUrl = "https://media.movieassets.com/static/images/items/movies/posters/500/100/spider-man-c09f709a5db1cd7d6c3dabb678d908e5.jpg",
                            ReleaseDate = new DateTime(2002, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spider-Man",
                            Type = 1
                        },
                        new
                        {
                            Id = 16,
                            Description = "When family man Nick Brewer is abducted in a crime with a sinister online twist, those closest to him race to uncover who is behind it and why.",
                            ImageUrl = "https://www.what-song.com/_next/image?url=https:%2F%2Fimage.tmdb.org%2Ft%2Fp%2Fw500%2Fq42t4S113jebD1khigJt8z3m1mD.jpg&w=828&q=75",
                            ReleaseDate = new DateTime(2021, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clickbait",
                            Type = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
                            ImageUrl = "https://i1.wp.com/www.realhypegh.com/wp-content/uploads/2021/09/Money-Heist.jpg?resize=696%2C1031&ssl=1",
                            ReleaseDate = new DateTime(2017, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Money Heist",
                            Type = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Nine stressed city dwellers visit a boutique health-and-wellness resort that promises healing and transformation. The resort's director is a woman on a mission to reinvigorate their tired minds and bodies.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.yclr5qYMsedWaCB1yJRQdgHaLU?pid=ImgDet&rs=1",
                            ReleaseDate = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nine Perfect Strangers",
                            Type = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Sheriff Deputy Rick Grimes wakes up from a coma to learn the world is in ruins and must lead a group of survivors to stay alive.",
                            ImageUrl = "https://th.bing.com/th/id/R.b904983728868f3ed5ce79fb819c8699?rik=LmhMRcd0HZRPew&riu=http%3a%2f%2fpics.filmaffinity.com%2fThe_Walking_Dead_TV_Series-285470099-large.jpg&ehk=8lZYkdu%2fiSDQQ%2f9RKV8aveMd7qagFCj573%2fZ1rNnfzQ%3d&risl=&pid=ImgRaw&r=0",
                            ReleaseDate = new DateTime(2010, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Walking Dead",
                            Type = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
                            ImageUrl = "https://th.bing.com/th/id/R.e024c02d31c823d7d68e23550207fb3e?rik=p3JUYI%2bmYV91RA&pid=ImgRaw&r=0",
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game of Thrones",
                            Type = 2
                        },
                        new
                        {
                            Id = 21,
                            Description = "A commercial airliner suddenly reappears after being missing for five years. As those aboard reintegrate into society, they experience guiding voices and visions of events yet to occur, and soon a deeper mystery unfolds.",
                            ImageUrl = "https://image.tmdb.org/t/p/original/moaCMoZYVifaQnNJGDr3M6rBglB.jpg",
                            ReleaseDate = new DateTime(2018, 9, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Manifest",
                            Type = 2
                        },
                        new
                        {
                            Id = 22,
                            Description = "Comedy series following the exploits of Det. Jake Peralta and his diverse, lovable colleagues as they police the NYPD's 99th Precinct.",
                            ImageUrl = "https://th.bing.com/th/id/R.6ed153b03e7aae27d1c14006c3ffd4eb?rik=E9ceeJRcwZwm5w&pid=ImgRaw&r=0",
                            ReleaseDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Brooklyn Nine-Nine",
                            Type = 2
                        },
                        new
                        {
                            Id = 23,
                            Description = "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
                            ImageUrl = "https://th.bing.com/th/id/R.7daca6eab99b67e6cd63f01bfdf3a41a?rik=QqKBdpltIOVmrw&riu=http%3a%2f%2fwww.notrecinema.com%2fimages%2fcache%2fbreaking-bad-poster_399299_31440.jpg&ehk=YPzSvSux8LNPKZgfHqAfYce7Rz6%2fafdR6GZvT1TE6J8%3d&risl=&pid=ImgRaw&r=0",
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breaking Bad",
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            Description = "Follows the personal and professional lives of six twenty to thirty-something-year-old friends living in Manhattan.",
                            ImageUrl = "https://images.saymedia-content.com/.image/t_share/MTc2NTc0ODUzMDQ0Nzc0NjE5/tv-shows-like-friends.jpg",
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Friends",
                            Type = 2
                        },
                        new
                        {
                            Id = 25,
                            Description = "Due to a political conspiracy, an innocent man is sent to death row and his only hope is his brother, who makes it his mission to deliberately get himself sent to the same prison in order to break the both of them out, from the inside.",
                            ImageUrl = "https://cdn.cinematerial.com/p/500x/rkevtzje/prison-break-movie-cover.jpg",
                            ReleaseDate = new DateTime(2005, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Prison Break",
                            Type = 2
                        },
                        new
                        {
                            Id = 26,
                            Description = "The cases of the F.B.I. Behavioral Analysis Unit (B.A.U.), an elite group of profilers who analyze the nation's most dangerous serial killers and individual heinous crimes in an effort to anticipate their next moves before they strike again.",
                            ImageUrl = "https://th.bing.com/th/id/OIP.ZUzAwzdzq780bQ9KjtJ2xgHaKd?pid=ImgDet&rs=1",
                            ReleaseDate = new DateTime(2005, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Criminal Minds",
                            Type = 2
                        },
                        new
                        {
                            Id = 27,
                            Description = "The series focuses on the rise and fall of Mughal Empire through generations from Babur to Aurangzeb.",
                            ImageUrl = "https://i1.wp.com/hdmoviez.biz/wp-content/uploads/2021/08/The-Empire-2021-S01.png?w=500",
                            ReleaseDate = new DateTime(2021, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Empire",
                            Type = 2
                        },
                        new
                        {
                            Id = 28,
                            Description = "A new FBI profiler, Elizabeth Keen, has her entire life uprooted when a mysterious criminal, Raymond Reddington, who has eluded capture for decades, turns himself in and insists on speaking only to her.",
                            ImageUrl = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6259/6259110_so.jpg",
                            ReleaseDate = new DateTime(2013, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Blacklist",
                            Type = 2
                        },
                        new
                        {
                            Id = 29,
                            Description = "An antisocial maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come his way using his crack team of doctors and his wits.",
                            ImageUrl = "https://www.pelisxd.com/wp-content/uploads/2020/04/house-15611-poster.jpg",
                            ReleaseDate = new DateTime(2004, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "House",
                            Type = 2
                        },
                        new
                        {
                            Id = 30,
                            Description = "Max McLaughlin is an American cop who arrives in Berlin in the summer of 1946 to help create a police force in the chaotic aftermath of the war.",
                            ImageUrl = "https://d2iltjk184xms5.cloudfront.net/uploads/photo/file/382771/e6aace1d14a77a2badd179ba926ac1b3-defeatedposter.jpg",
                            ReleaseDate = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Defeated",
                            Type = 2
                        });
                });

            modelBuilder.Entity("JAP_Task_Backend.Models.VideoActor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VideoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("VideoActors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tom Hanks",
                            VideoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Matt Damon",
                            VideoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Leonardo DiCaprio",
                            VideoId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Joseph Gordon-Levitt",
                            VideoId = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Henry Cavill",
                            VideoId = 3
                        },
                        new
                        {
                            Id = 6,
                            Name = "Anna Shaffer",
                            VideoId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Tom Hanks",
                            VideoId = 4
                        },
                        new
                        {
                            Id = 8,
                            Name = "Robin Wright",
                            VideoId = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Brad Pitt",
                            VideoId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "Edward Norton",
                            VideoId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Will Smith",
                            VideoId = 6
                        },
                        new
                        {
                            Id = 12,
                            Name = "Martin Lawrence",
                            VideoId = 6
                        },
                        new
                        {
                            Id = 13,
                            Name = "Will Smith",
                            VideoId = 7
                        },
                        new
                        {
                            Id = 14,
                            Name = "Martin Lawrence",
                            VideoId = 7
                        },
                        new
                        {
                            Id = 15,
                            Name = "Will Smith",
                            VideoId = 8
                        },
                        new
                        {
                            Id = 16,
                            Name = "Martin Lawrence",
                            VideoId = 8
                        },
                        new
                        {
                            Id = 17,
                            Name = "Chris Pratt",
                            VideoId = 9
                        },
                        new
                        {
                            Id = 18,
                            Name = "Yvonne Strahovski",
                            VideoId = 9
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sam Neill",
                            VideoId = 10
                        },
                        new
                        {
                            Id = 20,
                            Name = "Laura Dern",
                            VideoId = 10
                        },
                        new
                        {
                            Id = 21,
                            Name = "Jeff Goldblum",
                            VideoId = 11
                        },
                        new
                        {
                            Id = 22,
                            Name = "Julianne Moore",
                            VideoId = 11
                        },
                        new
                        {
                            Id = 23,
                            Name = "Sam Neill",
                            VideoId = 12
                        },
                        new
                        {
                            Id = 24,
                            Name = "William H. Macy",
                            VideoId = 12
                        },
                        new
                        {
                            Id = 25,
                            Name = "Chris Pratt",
                            VideoId = 13
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bryce Dallas Howard",
                            VideoId = 13
                        },
                        new
                        {
                            Id = 27,
                            Name = "Chris Pratt",
                            VideoId = 14
                        },
                        new
                        {
                            Id = 28,
                            Name = "Bryce Dallas Howard",
                            VideoId = 14
                        },
                        new
                        {
                            Id = 29,
                            Name = "Tobey Maguire",
                            VideoId = 15
                        },
                        new
                        {
                            Id = 30,
                            Name = "Kristen Dunst",
                            VideoId = 15
                        },
                        new
                        {
                            Id = 31,
                            Name = "Zoe Kazan",
                            VideoId = 16
                        },
                        new
                        {
                            Id = 32,
                            Name = "Betty Gabriel",
                            VideoId = 16
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ursula Cobero",
                            VideoId = 17
                        },
                        new
                        {
                            Id = 34,
                            Name = "Alvaro Morte",
                            VideoId = 17
                        },
                        new
                        {
                            Id = 35,
                            Name = "Nicole Kidman",
                            VideoId = 18
                        },
                        new
                        {
                            Id = 36,
                            Name = "Melissa McCarthy",
                            VideoId = 18
                        },
                        new
                        {
                            Id = 37,
                            Name = "Andrew Lincoln",
                            VideoId = 19
                        },
                        new
                        {
                            Id = 38,
                            Name = "Norman Reedus",
                            VideoId = 19
                        },
                        new
                        {
                            Id = 39,
                            Name = "Emilia Clarke",
                            VideoId = 20
                        },
                        new
                        {
                            Id = 40,
                            Name = "Peter Dinklage",
                            VideoId = 20
                        },
                        new
                        {
                            Id = 41,
                            Name = "Melissa Roxburgh",
                            VideoId = 21
                        },
                        new
                        {
                            Id = 42,
                            Name = "Josh Dallas",
                            VideoId = 21
                        },
                        new
                        {
                            Id = 43,
                            Name = "Andy Samberg",
                            VideoId = 22
                        },
                        new
                        {
                            Id = 44,
                            Name = "Stephanie Beatriz",
                            VideoId = 22
                        },
                        new
                        {
                            Id = 45,
                            Name = "Bryan Cranston",
                            VideoId = 23
                        },
                        new
                        {
                            Id = 46,
                            Name = "Aaron Paul",
                            VideoId = 23
                        },
                        new
                        {
                            Id = 47,
                            Name = "Jennifer Aniston",
                            VideoId = 24
                        },
                        new
                        {
                            Id = 48,
                            Name = "Courteney Cox",
                            VideoId = 24
                        },
                        new
                        {
                            Id = 49,
                            Name = "Dominic Purcell",
                            VideoId = 25
                        },
                        new
                        {
                            Id = 50,
                            Name = "Wentworth Miller",
                            VideoId = 25
                        },
                        new
                        {
                            Id = 51,
                            Name = "Matthew Gray Gubler",
                            VideoId = 26
                        },
                        new
                        {
                            Id = 52,
                            Name = "Kristen Vangsness",
                            VideoId = 26
                        },
                        new
                        {
                            Id = 53,
                            Name = "Shabana Azmi",
                            VideoId = 27
                        },
                        new
                        {
                            Id = 54,
                            Name = "Kunal Kapoor",
                            VideoId = 27
                        },
                        new
                        {
                            Id = 55,
                            Name = "James Spader",
                            VideoId = 28
                        },
                        new
                        {
                            Id = 56,
                            Name = "Megane Boone",
                            VideoId = 28
                        },
                        new
                        {
                            Id = 57,
                            Name = "Hugh Lauri",
                            VideoId = 29
                        },
                        new
                        {
                            Id = 58,
                            Name = "Omar Epps",
                            VideoId = 29
                        },
                        new
                        {
                            Id = 59,
                            Name = "Taylor Kitsch",
                            VideoId = 30
                        },
                        new
                        {
                            Id = 60,
                            Name = "Michael C. Hall",
                            VideoId = 30
                        });
                });

            modelBuilder.Entity("JAP_Task_Backend.Models.Rating", b =>
                {
                    b.HasOne("JAP_Task_Backend.Models.Video", "Video")
                        .WithMany("Ratings")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("JAP_Task_Backend.Models.VideoActor", b =>
                {
                    b.HasOne("JAP_Task_Backend.Models.Video", "Video")
                        .WithMany("Actors")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("JAP_Task_Backend.Models.Video", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
